# this code base on billing 
medicine_name = str(input("enter the name of medicine name = "))
strip_quantity = int(input("enter the quantity of medicien = "))
price = int(input("price of medicine is = "))

total_amount = (price*strip_quantity)
final_bill = (total_amount - 50)
print(f"you purchase {medicine_name} and you get {strip_quantity} strips \n your final  bill is {final_bill}\n thanks for comming 😊")
# this code base on calculator 
a = int(input("enter the first number = "))
b = float(input("enter the second number ="))
Addison = (a+b)
multiplication = (a*b)
substruction = (a-b)
division = (a/b)
print(f"Addison = {Addison} \n multiplication = {multiplication} \n substruction = {substruction} \n division{division}")
# this code base on result makeing 
student_name = str(input("Enter student name = "))
subject_name = str(input("Enter subject name = "))
subject_marks = int(input("Enter mark you earn = "))
subject_name1 = str(input("Enter subject name = "))
subject_marks1 = int(input("Enter mark you earn = "))
subject_name2 = str(input("Enter subject name = "))
subject_marks2 = int(input("Enter mark you earn = "))
subject_name3 = str(input("Enter subject name = "))
subject_marks3 = int(input("Enter mark you earn = "))
total_mark = (subject_marks+subject_marks1+subject_marks2+subject_marks3)
Percentage = ((total_mark/400)*100)
print(f"---RTU 4th Sem Result--- \nstudent name = {student_name} \nTotal mark = {total_mark} | Percentage = {Percentage} \n----------------------------")
